{% set name = "mesa-geo" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b0af1bc36661be5b193c1d3edbbf94518a2afed2b9e1ef074fa34cf665e0c124

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - mesa >=2.1.0,<2.2.dev0
    - pip
  run:
    - python >=3.8
    - mesa >=2.1.0,<2.2.dev0
    - geopandas
    - libpysal
    - rtree
    - rasterio
    - shapely
    - numpy
    - pyproj
    - folium
    - xyzservices >=2022.9.0

test:
  imports:
    - mesa_geo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/projectmesa/mesa-geo
  summary: GIS extension for the Mesa agent-based modeling framework in Python
  description: |
    Mesa-Geo implements a GeoSpace that can host GIS-based GeoAgents, which are like normal Agents, 
    except they have a geometry attribute that is a Shapely object and a crs attribute for its Coordinate Reference System. 
    You can use Shapely directly to create arbitrary geometries, but in most cases you will want to import your geometries from a file. 
    Mesa-Geo allows you to create GeoAgents from any vector data file (e.g. shapefiles), valid GeoJSON objects or a GeoPandas GeoDataFrame.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/projectmesa/mesa-geo
  doc_url: http://mesa-geo.readthedocs.org/en/main/

extra:
  recipe-maintainers:
    - mfisher87
    - adamamer20
